<a href="https://colab.research.google.com/github/sbustos497/cd_202202_Santiago_Bustos/blob/master/Taller_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pyproj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyproj
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 7.9 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from pyproj) (2022.6.15)
Installing collected packages: pyproj
Successfully installed pyproj-3.2.1

In [2]:
import pandas as pd

In [3]:
ruta = 'https://foscalinternacional.com/datasets/eventos_dengue_2020.csv'
df = pd.read_csv(ruta)

In [4]:
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,hipotension,hepatomegalia,hemorragia_mucosa,hipotermia,caida_plaquetas,acum_liquido,aum_hematocrito,conducta,latitud,longitud
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.076011,-73.102501
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.079495,-73.105400
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.090290,-73.091003
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.067435,-73.090958
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2,2,2,2,1,2,2,2. Hospitalizacion piso,7.066905,-73.104980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,2,2,1,2,2,2,2,1. Ambulatorio,7.072610,-73.099487
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,2,2,2,2,1,2,1,2. Hospitalizacion piso,7.065252,-73.103607
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.091391,-73.103264
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,2,2,2,2,2,2,2,1. Ambulatorio,7.061083,-73.097000
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2,2,2,2,2,2,2,2. Hospitalizacion piso,7.062521,-73.080444

In [5]:
df.dtypes

ID                     int64
fec_not               object
semana                 int64
año                    int64
edad_                  int64
uni_med_               int64
sexo_                 object
cod_pais_o             int64
cod_dpto_o             int64
cod_mun_o              int64
area_                  int64
ocupacion_             int64
tip_ss_               object
cod_ase_              object
gp_discapa             int64
gp_desplaz             int64
gp_migrant             int64
gp_carcela             int64
gp_gestan              int64
gp_calle               int64
gp_psiquia             int64
gp_vic_vio             int64
fecha_contagio        object
inicio_sintomas       object
pac_hos_               int64
fec_hos_              object
condicion_final        int64
fecha_defuncion      float64
fecha_nacimiento      object
certif_defuncion     float64
familiar_sintomas      int64
fiebre                 int64
cefalea                int64
dolor_retroocular      int64
mialgias               int64
artralgia              int64
erupcion               int64
dolor_abdomen          int64
vomito                 int64
diarrea                int64
somnolencia            int64
hipotension            int64
hepatomegalia          int64
hemorragia_mucosa      int64
hipotermia             int64
caida_plaquetas        int64
acum_liquido           int64
aum_hematocrito        int64
conducta              object
latitud              float64
longitud             float64
dtype: object

In [6]:
from datetime import datetime
df['fec_not2'] = pd.to_datetime(df['fec_not'],format='%d/%m/%Y')

In [7]:
df['fecha_contagio2'] = pd.to_datetime(df['fecha_contagio'],format='%d/%m/%Y')
df['inicio_sintomas2'] = pd.to_datetime(df['inicio_sintomas'],format='%d/%m/%Y')
df['fec_hos2'] = pd.to_datetime(df['fec_hos_'],format='%d/%m/%Y')

In [36]:
import pyproj
P = pyproj.Proj(proj = 'utm',zone=18,ellps='WGS84',preserve_units=True)
df['x'], df['y']=P(df['latitud'], df['longitud'])
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,conducta,latitud,longitud,fec_not2,fecha_contagio2,inicio_sintomas2,fec_hos2,x,y,distancia
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,1. Ambulatorio,7.076011,-73.102501,2020-01-17,2020-01-17,2020-01-10,NaT,2.394617e+06,-9.730308e+06,2308.590940
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,1. Ambulatorio,7.079495,-73.105400,2020-01-10,2020-01-10,2020-01-07,NaT,2.394299e+06,-9.730473e+06,2801.363574
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,1. Ambulatorio,7.090290,-73.091003,2020-01-12,2020-01-12,2020-01-08,NaT,2.396012e+06,-9.730594e+06,3069.373505
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,1. Ambulatorio,7.067435,-73.090958,2020-01-12,2020-01-10,2020-01-06,NaT,2.395905e+06,-9.729826e+06,722.357045
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2. Hospitalizacion piso,7.066905,-73.104980,2020-01-10,2020-01-10,2020-01-07,2020-01-10,2.394286e+06,-9.730044e+06,2120.863283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,1. Ambulatorio,7.072610,-73.099487,2020-03-07,2020-03-06,2020-03-03,NaT,2.394947e+06,-9.730143e+06,1815.492273
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,2. Hospitalizacion piso,7.065252,-73.103607,2020-03-13,2020-03-13,2020-03-06,2020-03-13,2.394437e+06,-9.729966e+06,1940.368049
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,1. Ambulatorio,7.091391,-73.103264,2020-03-08,2020-03-08,2020-03-04,NaT,2.394604e+06,-9.730836e+06,3666.846438
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,1. Ambulatorio,7.061083,-73.097000,2020-03-11,2020-03-11,2020-03-05,NaT,2.395178e+06,-9.729715e+06,1211.553222
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2. Hospitalizacion piso,7.062521,-73.080444,2020-03-09,2020-03-06,2020-03-02,2020-03-06,2.397093e+06,-9.729485e+06,637.540178

In [41]:
#punto de la alcaldia
lat_alcaldia = 7.062958503050063
lon_alcaldia = -73.08619741888012
x_alcaldia , y_alcaldia = P(lat_alcaldia,lon_alcaldia)
x_alcaldia , y_alcaldia

(2396432.1637429222, -9729596.275358902)

In [42]:
#metodo que haya la distancia 
import numpy as np
def distancia(x1,y1,x2,y2):

  d = np.sqrt((x_alcaldia - df['x'])**2 + (y_alcaldia - df['y'])**2)

  return d

In [43]:

df['distancia'] = np.sqrt((x_alcaldia - df['x'])**2 + (y_alcaldia - df['y'])**2)

In [44]:
df

,ID,fec_not,semana,año,edad_,uni_med_,sexo_,cod_pais_o,cod_dpto_o,cod_mun_o,...,conducta,latitud,longitud,fec_not2,fecha_contagio2,inicio_sintomas2,fec_hos2,x,y,distancia
0,1,17/01/2020,1,2020,25,1,F,170,68,276,...,1. Ambulatorio,7.076011,-73.102501,2020-01-17,2020-01-17,2020-01-10,NaT,2.394617e+06,-9.730308e+06,1949.996576
1,2,10/01/2020,1,2020,24,1,M,170,68,276,...,1. Ambulatorio,7.079495,-73.105400,2020-01-10,2020-01-10,2020-01-07,NaT,2.394299e+06,-9.730473e+06,2305.990923
2,3,12/01/2020,1,2020,58,1,M,170,68,276,...,1. Ambulatorio,7.090290,-73.091003,2020-01-12,2020-01-12,2020-01-08,NaT,2.396012e+06,-9.730594e+06,1082.681722
3,4,12/01/2020,1,2020,29,1,F,170,68,276,...,1. Ambulatorio,7.067435,-73.090958,2020-01-12,2020-01-10,2020-01-06,NaT,2.395905e+06,-9.729826e+06,574.915400
4,5,10/01/2020,1,2020,56,1,F,170,68,276,...,2. Hospitalizacion piso,7.066905,-73.104980,2020-01-10,2020-01-10,2020-01-07,2020-01-10,2.394286e+06,-9.730044e+06,2192.053820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1258,7/03/2020,9,2020,36,1,F,170,68,276,...,1. Ambulatorio,7.072610,-73.099487,2020-03-07,2020-03-06,2020-03-03,NaT,2.394947e+06,-9.730143e+06,1582.301993
1258,1259,13/03/2020,9,2020,42,1,M,170,68,276,...,2. Hospitalizacion piso,7.065252,-73.103607,2020-03-13,2020-03-13,2020-03-06,2020-03-13,2.394437e+06,-9.729966e+06,2029.495620
1259,1260,8/03/2020,9,2020,2,1,M,170,68,276,...,1. Ambulatorio,7.091391,-73.103264,2020-03-08,2020-03-08,2020-03-04,NaT,2.394604e+06,-9.730836e+06,2209.259268
1260,1261,11/03/2020,9,2020,12,1,F,170,68,276,...,1. Ambulatorio,7.061083,-73.097000,2020-03-11,2020-03-11,2020-03-05,NaT,2.395178e+06,-9.729715e+06,1259.996774
1261,1262,9/03/2020,9,2020,14,1,M,170,68,276,...,2. Hospitalizacion piso,7.062521,-73.080444,2020-03-09,2020-03-06,2020-03-02,2020-03-06,2.397093e+06,-9.729485e+06,670.361113